## Description of Dataset

In [42]:
import pandas as pd
import numpy as np

## Import Dataset

In [44]:
def import_dataset(path):
    df=pd.read_csv(path)
    return df

## Separate Columns

In [76]:
def get_columns(df):
    numeric_cols = df.select_dtypes(include=[np.number,np.int64,np.float64]).columns.tolist()
    categorical_cols=df.select_dtypes(include=['category','object']).columns.tolist()
    print(f'Number of numeric columns are {len(numeric_cols)} and categorical columns are {len(categorical_cols)}')
    return  numeric_cols,categorical_cols

In [37]:
path="C:\\Users\\hp\Downloads\\ML-EdgeIIoT-dataset.csv\\dataset.csv"
df=import_dataset(path)

C:\Users\hp\AppData\Local\Temp\ipykernel_6160\1775356972.py:2: DtypeWarning: Columns (3,6,11,13,14,15,16,17,31,32,34,39,45,51,54,55) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(path)

In [38]:
df.head()

,frame.time,ip.src_host,ip.dst_host,arp.dst.proto_ipv4,arp.opcode,arp.hw.size,arp.src.proto_ipv4,icmp.checksum,icmp.seq_le,icmp.transmit_timestamp,...,mqtt.proto_len,mqtt.protoname,mqtt.topic,mqtt.topic_len,mqtt.ver,mbtcp.len,mbtcp.trans_id,mbtcp.unit_id,Attack_label,Attack_type
0,6.0,192.168.0.152,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,MITM
1,6.0,192.168.0.101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,MITM
2,6.0,192.168.0.152,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,MITM
3,6.0,192.168.0.101,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,MITM
4,6.0,192.168.0.152,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,MITM

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157800 entries, 0 to 157799
Data columns (total 63 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   frame.time                 157800 non-null  object
 1   ip.src_host                157800 non-null  object
 2   ip.dst_host                157800 non-null  object
 3   arp.dst.proto_ipv4         157800 non-null  object
 4   arp.opcode                 157800 non-null  float64
 5   arp.hw.size                157800 non-null  float64
 6   arp.src.proto_ipv4         157800 non-null  object
 7   icmp.checksum              157800 non-null  float64
 8   icmp.seq_le                157800 non-null  float64
 9   icmp.transmit_timestamp    157800 non-null  float64
 10  icmp.unused                157800 non-null  float64
 11  http.file_data             157800 non-null  object
 12  http.content_length        157800 non-null  float64
 13  http.request.uri.query     157800 non-null  object
 14  http.request.method        157800 non-null  object
 15  http.referer               157800 non-null  object
 16  http.request.full_uri      157800 non-null  object
 17  http.request.version       157800 non-null  object
 18  http.response              157800 non-null  float64
 19  http.tls_port              157800 non-null  float64
 20  tcp.ack                    157800 non-null  float64
 21  tcp.ack_raw                157800 non-null  float64
 22  tcp.checksum               157800 non-null  float64
 23  tcp.connection.fin         157800 non-null  float64
 24  tcp.connection.rst         157800 non-null  float64
 25  tcp.connection.syn         157800 non-null  float64
 26  tcp.connection.synack      157800 non-null  float64
 27  tcp.dstport                157800 non-null  float64
 28  tcp.flags                  157800 non-null  float64
 29  tcp.flags.ack              157800 non-null  float64
 30  tcp.len                    157800 non-null  float64
 31  tcp.options                157800 non-null  object
 32  tcp.payload                157800 non-null  object
 33  tcp.seq                    157800 non-null  float64
 34  tcp.srcport                157800 non-null  object
 35  udp.port                   157800 non-null  float64
 36  udp.stream                 157800 non-null  float64
 37  udp.time_delta             157800 non-null  float64
 38  dns.qry.name               157800 non-null  float64
 39  dns.qry.name.len           157800 non-null  object
 40  dns.qry.qu                 157800 non-null  float64
 41  dns.qry.type               157800 non-null  float64
 42  dns.retransmission         157800 non-null  float64
 43  dns.retransmit_request     157800 non-null  float64
 44  dns.retransmit_request_in  157800 non-null  float64
 45  mqtt.conack.flags          157800 non-null  object
 46  mqtt.conflag.cleansess     157800 non-null  float64
 47  mqtt.conflags              157800 non-null  float64
 48  mqtt.hdrflags              157800 non-null  float64
 49  mqtt.len                   157800 non-null  float64
 50  mqtt.msg_decoded_as        157800 non-null  float64
 51  mqtt.msg                   157800 non-null  object
 52  mqtt.msgtype               157800 non-null  float64
 53  mqtt.proto_len             157800 non-null  float64
 54  mqtt.protoname             157800 non-null  object
 55  mqtt.topic                 157800 non-null  object
 56  mqtt.topic_len             157800 non-null  float64
 57  mqtt.ver                   157800 non-null  float64
 58  mbtcp.len                  157800 non-null  float64
 59  mbtcp.trans_id             157800 non-null  float64
 60  mbtcp.unit_id              157800 non-null  float64
 61  Attack_label               157800 non-null  int64
 62  Attack_type                157800 non-null  object
dtypes: float64(42), int64(1), object(20)
memory usage: 75.8+ MB

In [77]:
numeric_cols,categorical_cols=get_columns(df)

Number of numeric columns are 43 and categorical columns are 20